# ========================
# SERVER
# ========================
server.port=8080

# ========================
# DATASOURCE (PostgreSQL)
# ========================
spring.datasource.url=jdbc:postgresql://localhost:5432/db_otec_primavera
spring.datasource.username=postgres
spring.datasource.password=password.
spring.datasource.driver-class-name=org.postgresql.Driver

# ========================
# JPA / HIBERNATE
# ========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

# ========================
# THYMELEAF
# ========================
spring.thymeleaf.cache=false

# ========================
# LOGGING
# ========================
logging.level.root=INFO
logging.level.com.otec.primavera=INFO
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=INFO
